### ISSUE TITLE
为什么不用flink on yarn？

### ISSUE THREAD

**Issue by yqwoe** [wxgzgl/LarkMidTable#6]
为什么不用yarn？用xxl-job分布式调度感觉还是不合适。

**Comment by wxgzgl** [comment]
> 为什么不用yarn？用xxl-job分布式调度感觉还是不合适。
支持yarn的，不过目前开源的初期，还没有时间去测试yarn环境，xxl-job后续会换成Dolphin，如果可以，可以加入star我们，并加入我们

**Comment by yqwoe** [comment]
对于datax-web是分为管理界面，执行器(executor)，其实从抽象上来说，是master（管理、调度）和worker（执行）的概念。 对于flink本身是支持yarn，这里的执行器可以是flinkx本身，调度和管理交给yarn来做好了。因为我之前做过datax的相关项目，我的理解可能是站在我的角度。
