### ISSUE TITLE
缺少com.wugui:datax-core2.1.2

### ISSUE THREAD

**Issue by luofly** [wxgzgl/LarkMidTable#68]
大佬缺少com.wugui:datax-core2.1.2 啊

**Comment by wxgzgl** [comment]
代码不是最新版本，重新拉代码，如果有问题加我微信 LarkMidTable2021


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxgzgl/LarkMidTable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月15日(星期六) 下午4:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wxgzgl/LarkMidTable] 缺少com.wugui:datax-core2.1.2 (Issue #68)





 
大佬缺少com.wugui:datax-core2.1.2 啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wxgzgl** [comment]
project close
